import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "@/styles/globals.css";
import Navbar from "@/components/navbar";
import Footer from "@/components/footer";

const poppins = Poppins({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.className} bg-black text-white`}>
        <div className="flex items-center justify-center w-full h-screen px-4 md:px-8">
          <div className="flex flex-col items-start justify-start max-w-2xl w-full h-screen pt-16">
            <Navbar />
            <div className="mt-20">{children}</div>
            <Footer />
          </div>
        </div>
      </body>
    </html>
  );
}
